### ISSUE TITLE
Private functions are missed from the generated stubs.

### ISSUE THREAD

**Issue by proofit404** [kialo/stubalyzer#6]
If I had a code like this:
```python
def _is_attrs(entity):
    if IS_AVAILABLE:
        return inspect.isclass(entity) and attr.has(entity)
    else:
        return False  # pragma: no cover
```
It will give me error:
```
Symbol "_mappers.entities.attrs._is_attrs" not found in generated stubs
```
Is it intended?

Thanks for the awesome project!

Have a good day :tada: 

Best regards,
Artem.

**Comment by barbagianni** [comment]
Hi Artem!

The situation looks like your stubs contain the type while stubgen does not generate it.

Did you define a type for `_is_attrs`?

Best, David

**Comment by proofit404** [comment]
Hi David,

Thanks for the response!

You can see the code [here](https://github.com/dry-python/mappers/blob/1e1c4d379d51e2cd1e3a462ab339812f21c0317b/src/_mappers/entities/attrs.py) and stubs [here](https://github.com/dry-python/mappers/blob/1e1c4d379d51e2cd1e3a462ab339812f21c0317b/src/_mappers/entities/attrs.pyi).

Best regards,
Artem.

**Comment by barbagianni** [comment]
By default stubgen (which is used to generate the reference stubs) will not generate definitions for what it considers private (see [here](https://mypy.readthedocs.io/en/stable/stubgen.html#cmdoption-stubgen-include-private)). We didn't need this so far, but if this is a use case, then we could introduce this as a pass through option for stubgen.

Best

**Comment by proofit404** [comment]
Yes, the option would be a perfect solution for me.

**Comment by barbagianni** [comment]
Hi Artem, I added a pass through for the --include-private flag to v0.3.0.

**Comment by proofit404** [comment]
Thank you so much!
